Repository GihoKo/taskify_team8, pull requests merged in 2024-03, with the labels that each got.

#14 [Feat] git action workflow
  .github/workflows/lint-check.yml
  app/layout.tsx
  components/portal/Portal.tsx
  hooks/use-modal/context/ModalContext.ts
  hooks/use-modal/context/ModalsContext.ts
  hooks/use-modal/index.ts
  hooks/use-modal/legacy/useModal.tsx
  hooks/use-modal/modal-component/Modal.tsx
  hooks/use-modal/modal-component/Modals.tsx
  hooks/use-modal/provider/ModalListProvider.tsx
  hooks/use-modal/provider/ModalProvider.tsx
  hooks/use-modal/types.ts
  hooks/use-modal/useCloseModal.ts
  hooks/use-modal/useModal.ts
  hooks/use-modal/useModalList.ts
  hooks/useMountedState.ts
  hooks/useToggle.ts
  interface/.gitkeep
  tsconfig.json
Labels: fix, !HOTFIX

#17 Feat: svg 이미지 ReactComponent화 하기위한 @svgr webpack 세팅
  @types/svg.d.ts
  next.config.mjs
  package-lock.json
  package.json
  svgo.config.js
Labels: feat

#20 Feat: myDashboard Page 여러 컴포넌트 디자인 구현
  .vscode/settings.json
  app/mydashboard/_components/atoms/CreateDashboardChip.tsx
  app/mydashboard/_components/atoms/InvitationButton.tsx
  app/mydashboard/_components/atoms/PageNationButton.tsx
  app/mydashboard/_components/atoms/PageNationText.tsx
  app/mydashboard/_components/molecules/CreateDashboardButton.tsx
  app/mydashboard/_components/organisms/DashboardButton.tsx
  app/mydashboard/_components/templates/.gitkeep
  app/mydashboard/page.tsx
  app/page.tsx
  public/images/icons/add.svg
  public/images/icons/icon-crown.svg
  public/images/icons/icon-right-arrow.svg
  public/images/icons/icon-search.svg
  public/images/icons/pagenation-left-arrow.svg
  public/images/icons/pagenation-right-arrow.svg
  public/images/mockImg.png
  public/images/no-invited.svg
Labels: feat, design

#25 !HOTFIX: box-sizing border-box로 수정
  styles/global.css
Labels: !HOTFIX

#26 Feat: dashboardBox 및 하위 컴포넌트 디자인 구현
  app/mydashboard/_components/atoms/PageNationText.tsx
  app/mydashboard/_components/molecules/PageNationWrapper.tsx
  app/mydashboard/_components/organisms/DashboardBox.tsx
  app/mydashboard/_components/organisms/DashboardContainer.tsx
  app/mydashboard/_components/organisms/DashboardItem.tsx
  app/mydashboard/page.tsx
  styles/global.css
Labels: feat, design

#34 Feat: Todo 모달 atoms molecules 작성.
  components/atoms/.gitkeep
  components/atoms/ColumnNameBadge.tsx
  components/atoms/ListItem.tsx
  components/atoms/ProfileImage.tsx
  components/atoms/TagBadge.tsx
  components/molecules/.gitkeep
  components/molecules/AssigneeInformation.tsx
  components/molecules/ListGroup.tsx
  components/molecules/Reply.tsx
  components/molecules/ReplyInputForm.tsx
  components/molecules/TagBadgeContainer.tsx
  components/organisms/ReplyArea.tsx
  constants/.gitkeep
  constants/BadgeColor.ts
  hooks/.gitkeep
  public/images/icons/close-icon.svg
  public/images/icons/ellipse.svg
  public/images/icons/horizontal-divder.svg
  public/images/icons/kebab-icon.svg
  public/images/icons/profile-default-icon.svg
Labels: feat, style

#35 Feat: 칼럼 모달에 사용되는 버튼,인풋 디자인 구현.
  app/dashboard/[dashboardId]/_column/_components/atoms/ColumnButton.tsx
  app/dashboard/[dashboardId]/_column/_components/atoms/ColumnInput.tsx
  app/dashboard/[dashboardId]/page.tsx
Labels: feat, design

#30 Feat: 대시보드 카드 및 칼럼 구현
  app/dashboard/[dashboardId]/_components/atoms/CardColumn.tsx
  app/dashboard/[dashboardId]/_components/atoms/Cogwheel.tsx
  app/dashboard/[dashboardId]/_components/atoms/ColumnContainer.tsx
  app/dashboard/[dashboardId]/_components/atoms/ColumnList.tsx
  app/dashboard/[dashboardId]/_components/atoms/DueDate.tsx
  app/dashboard/[dashboardId]/_components/atoms/FirstLetterProfile.tsx
  app/dashboard/[dashboardId]/_components/atoms/NumberChip.tsx
  app/dashboard/[dashboardId]/_components/atoms/Page.tsx
  app/dashboard/[dashboardId]/_components/atoms/PlusShapeButton.tsx
  app/dashboard/[dashboardId]/_components/atoms/ProgressChip.tsx
  app/dashboard/[dashboardId]/_components/molecules/CardAppendRectangle.tsx
  app/dashboard/[dashboardId]/_components/molecules/ColumnAppenderRectangle.tsx
  app/dashboard/[dashboardId]/_components/molecules/ColumnProgressBar.tsx
  app/dashboard/[dashboardId]/_components/organisms/Card.tsx
  app/dashboard/[dashboardId]/_components/organisms/ColumnHeader.tsx
  app/page.tsx
  components/atoms/tag/CardTag.tsx
  constants/randomColorMap.tsx
  public/images/icons/add-box-unfilled.svg
  public/images/icons/card-append-img.svg
  public/images/icons/card-calendar.svg
  public/images/icons/cogwheel.svg
  public/images/mocks/card-mock-image.png
  utils/time/formatDateShorter.ts
Labels: feat, design

#32 Feat: InvitationBox 및 하위 컴포넌트 구현
  app/mydashboard/_components/atoms/InvitationButton.tsx
  app/mydashboard/_components/atoms/InvitationText.tsx
  app/mydashboard/_components/atoms/InvitationTitle.tsx
  app/mydashboard/_components/atoms/SearchIcon.tsx
  app/mydashboard/_components/molecules/InvitationButtonWrapper.tsx
  app/mydashboard/_components/molecules/InvitationDashboardName.tsx
  app/mydashboard/_components/molecules/InvitationHeader.tsx
  app/mydashboard/_components/molecules/InvitationInviteeName.tsx
  app/mydashboard/_components/molecules/InvitationSearchBar.tsx
  app/mydashboard/_components/organisms/InvitationBox.tsx
  app/mydashboard/_components/organisms/InvitationContainer.tsx
  app/mydashboard/_components/organisms/InvitationItem.tsx
  app/mydashboard/page.tsx
Labels: feat, design

#31 Feat: 대시보드 & 대시보드 수정 공통 네비게이션 바 구현
  .vscode/settings.json
  app/dashboard/[dashboardId]/_components/atoms/ButtonWithIcon.tsx
  app/dashboard/[dashboardId]/_components/molecules/DashboardMemberList.tsx
  app/dashboard/[dashboardId]/_components/molecules/InviteButton.tsx
  app/dashboard/[dashboardId]/_components/molecules/ManageButton.tsx
  app/dashboard/[dashboardId]/_components/organisms/DashboardNav.tsx
  app/dashboard/[dashboardId]/_constants/mockDashboardMemberList.ts
  app/dashboard/[dashboardId]/_utils/count/getVisibleProfileListCount.ts
  app/dashboard/[dashboardId]/_utils/count/isOverZero.ts
  app/dashboard/[dashboardId]/page.tsx
  hooks/useResizeObserver.ts
Labels: feat, style

#42 랜딩페이지 navbar, hero 컴포넌트 디자인 구현
  app/_components/Footer/index.tsx
  app/_components/Main/index.tsx
  app/_components/Navbar/index.tsx
  app/_components/commons/SIgnButton.tsx
  app/mydashboard/_components/mock/mock.ts
  app/page.tsx
  public/images/hero.png
  public/images/logos/logo-small-unfilled-w23-h37.svg
  public/images/logos/taskify-text-large-filledViolet5534DA-w198-h55.svg
  public/images/logos/taskify-text-small-unfilled-w80-h22.svg
Labels: feat, design

#47 랜딩 페이지 Main/section, Footer 디자인 구현
  app/_components/Footer/index.tsx
  app/_components/Main/index.tsx
  app/_components/Navbar/index.tsx
  app/_components/commons/SIgnButton.tsx
  app/_components/constants/index.tsx
  app/_components/mock/index.ts
  app/mydashboard/_components/atoms/CreateDashboardChip.tsx
  app/mydashboard/_components/atoms/InvitationButton.tsx
  app/mydashboard/_components/atoms/InvitationText.tsx
  app/mydashboard/_components/atoms/InvitationTitle.tsx
  app/mydashboard/_components/atoms/PageNationButton.tsx
  app/mydashboard/_components/atoms/PageNationText.tsx
  app/mydashboard/_components/atoms/SearchIcon.tsx
  app/mydashboard/_components/mock/mock.ts
  app/mydashboard/_components/molecules/CreateDashboardButton.tsx
  app/mydashboard/_components/molecules/InvitationButtonWrapper.tsx
  app/mydashboard/_components/molecules/InvitationDashboardName.tsx
  app/mydashboard/_components/molecules/InvitationHeader.tsx
  app/mydashboard/_components/molecules/InvitationInviterName.tsx
  app/mydashboard/_components/molecules/InvitationSearchBar.tsx
  app/mydashboard/_components/molecules/PageNationWrapper.tsx
  app/mydashboard/_components/organisms/DashboardContainer.tsx
  app/mydashboard/_components/organisms/DashboardItem.tsx
  app/mydashboard/_components/organisms/InvitationBox.tsx
  app/mydashboard/_components/organisms/InvitationContainer.tsx
  app/mydashboard/_components/organisms/InvitationItem.tsx
  app/page.tsx
  public/images/icons/add-filledViolet_5534DA-16w-16h.svg
  public/images/icons/crown-filledYellow-FDD446-w16-h12.svg
  public/images/icons/pagenation-left-arrow-fiiledBlack-333236-w16-h16.svg
  public/images/icons/pagenation-left-arrow-fiiledGray-D9D9D9-w16-h16.svg
  public/images/icons/pagenation-right-arrow-fiiledBlack-333236-w16-h16.svg
  public/images/icons/pagenation-right-arrow-fiiledGray-D9D9D9-w16-h16.svg
  public/images/icons/right-arrow-filled-black-333236-w18-h18.svg
  public/images/icons/search-filledBlack-333236-w22-h22.svg
  public/images/logos/envelope-filledGray_D9D9D9-w20-h20.svg
  public/images/logos/facebook-filledGray_D9D9D9-w22-h22.svg
  public/images/logos/instagram-filledGray_D9D9D9-w22-h22.svg
  public/images/logos/taskify-text-large-filledViolet_5534DA-w198-h55.svg
  public/images/logos/unInvited_filledGray_D9D9D9-w100-h100.svg
  public/images/mocks/dashboard-setting.png
  public/images/mocks/hero.png
  public/images/mocks/invitation-setting.png
  public/images/mocks/members-setting.png
  public/images/mocks/priority-feature.png
  public/images/mocks/todo-feature.png
Labels: feat, refactor, design

#53 마이 대시보드, 대시보드 공용 navbar 디자인 구현 및 공용 폴더로 이동
  app/dashboard/layout.tsx
  app/mydashboard/page.tsx
  components/organisms/DashboardNav.tsx
Labels: feat, design

#55 컬럼 모달 디자인 구현
  app/dashboard/[dashboardId]/_components/Columns/CreateColumnModal/index.tsx
  app/dashboard/[dashboardId]/_components/Columns/DeleteColumnModal/index.tsx
  app/dashboard/[dashboardId]/_components/Columns/UpdateColumnModal/index.tsx
  app/dashboard/[dashboardId]/_components/Columns/commons/ColumnButton.tsx
  app/dashboard/[dashboardId]/_components/Columns/commons/ColumnButtonWrap.tsx
  app/dashboard/[dashboardId]/_components/Columns/commons/ColumnInput.tsx
  app/dashboard/[dashboardId]/_components/Columns/commons/ColumnModalTitile.tsx
Labels: feat, design

#56 Feat: dashboard edit 페이지 컴포넌트 구현
  .eslintrc.cjs
  app/dashboard/[dashboardId]/_components/atoms/ColumnContainerGroup.tsx
  app/dashboard/[dashboardId]/_components/organisms/Card.tsx
  app/dashboard/[dashboardId]/edit/_components/ArrowLeftIcon/index.tsx
  app/dashboard/[dashboardId]/edit/_components/ArrowLeftIconButton/index.tsx
  app/dashboard/[dashboardId]/edit/_components/BaseButton/index.tsx
  app/dashboard/[dashboardId]/edit/_components/BaseInput/index.tsx
  app/dashboard/[dashboardId]/edit/_components/ColorSelectList/context/ColorSelectListContext.ts
  app/dashboard/[dashboardId]/edit/_components/ColorSelectList/hooks/useColorSelectListContext.ts
  app/dashboard/[dashboardId]/edit/_components/ColorSelectList/index.ts
  app/dashboard/[dashboardId]/edit/_components/ColorSelectList/provider/ColorSelectListProvider.tsx
  app/dashboard/[dashboardId]/edit/_components/ColorSelectList/ui/ColorChip.tsx
  app/dashboard/[dashboardId]/edit/_components/ColorSelectList/ui/Container.tsx
  app/dashboard/[dashboardId]/edit/_components/ContentArea/index.tsx
  app/dashboard/[dashboardId]/edit/_components/DashboardDeleteButton/index.tsx
  app/dashboard/[dashboardId]/edit/_components/DashboardInfoEditForm/index.tsx
  app/dashboard/[dashboardId]/edit/_components/InputWithLabel/index.tsx
  app/dashboard/[dashboardId]/edit/_components/InviteButton/index.tsx
  app/dashboard/[dashboardId]/edit/_components/InviteeListTable/index.tsx
  app/dashboard/[dashboardId]/edit/_components/InviteeManageForm/index.tsx
  app/dashboard/[dashboardId]/edit/_components/MemberListTable/index.tsx
  app/dashboard/[dashboardId]/edit/_components/MemberManageForm/index.tsx
  app/dashboard/[dashboardId]/edit/_components/PageTurner/context/PageTurnerContext.ts
  app/dashboard/[dashboardId]/edit/_components/PageTurner/index.ts
  app/dashboard/[dashboardId]/edit/_components/PageTurner/provider/PageTurnerProvider.tsx
  app/dashboard/[dashboardId]/edit/_components/PageTurner/ui/ButtonContainer.tsx
  app/dashboard/[dashboardId]/edit/_components/PageTurner/ui/CurrentPageDescriber.tsx
  app/dashboard/[dashboardId]/edit/_components/PageTurner/ui/PaginationLeftButton.tsx
  app/dashboard/[dashboardId]/edit/_components/PageTurner/ui/PaginationRightButton.tsx
  app/dashboard/[dashboardId]/edit/_components/PageTurner/ui/Wrapper.tsx
  app/dashboard/[dashboardId]/edit/_constants/mocks.ts
  app/dashboard/[dashboardId]/edit/page.tsx
  app/dashboard/_components/atoms/Page.tsx
  app/dashboard/layout.tsx
  components/atoms/CardTag.tsx
  components/atoms/FirstLetterProfile.tsx
  components/organisms/DashboardNav.tsx
  hooks/use-modal/types.ts
  hooks/use-modal/useModal.ts
  hooks/use-modal/useModalList.ts
  hooks/useInView.ts
  hooks/usePaginate.ts
  hooks/useResizeObserver.ts
  interface/style.ts
  public/images/icons/table-invitelist-add-box-filledWhite-w16-h16.svg
  styles/global.css
  styles/navbarHeight.ts
  styles/utils/responsiveButtonUtils.ts
Labels: feat, design

#59 Feat: 공용 사이드바 컴포넌트 디자인 구현
  app/mydashboard/_components/MyDashboardList/index.tsx
  app/mydashboard/_components/commons/PageNationButton.tsx
  app/mydashboard/_components/mock/mock.ts
  app/mydashboard/page.tsx
  components/atoms/ColoredDot.tsx
  components/atoms/PageNationButton.tsx
  components/mock/mock.ts
  components/organisms/SideBar.tsx
  public/images/icons/add-filledGray_787486-w20-w20.svg
  public/images/logos/logo-small-filledViolet-w28.82-h33.07.svg
  public/images/logos/taskify-text-small-filledViolet-w80-h22.svg
Labels: feat, design

#64 Feat: 마이 대시보드 전체 ui 배치 완성
  app/mydashboard/_components/InvitationList/InvitationItem.tsx
  app/mydashboard/_components/InvitationList/index.tsx
  app/mydashboard/_components/MyDashboardList/DashboardItem.tsx
  app/mydashboard/_components/MyDashboardList/index.tsx
  app/mydashboard/_components/commons/InvitationButton.tsx
  app/mydashboard/page.tsx
  components/organisms/SideBar.tsx
Labels: feat, design

#61 Feat: signin 구현 및 파일 정리
  apis/axios.tsx
  app/login/.gitkeep
  app/signin/_components/.gitkeep
  app/signin/_hooks/useToggle.tsx
  app/signin/page.tsx
  app/signup/.gitkeep
  app/signup/page.tsx
  components/molecules/Input.tsx
  components/molecules/ModalCheckIt.tsx
  hooks/use-modal/useSignModal.tsx
  public/images/icons/icon-eyesOff.svg
  public/images/icons/icon-eyesOn.svg
  public/images/icons/logoLogin.svg
  store/.gitkeep
  store/user.js
Labels: feat, fix

#62 Feat: Create,Modify card modal 작업
  app/dashboard/[dashboardId]/_components/Cards/CreateCardsModal.1.tsx
  app/dashboard/[dashboardId]/_components/Cards/TextInput.tsx
  app/dashboard/[dashboardId]/_components/Cards/atoms/ImageLabel.tsx
  app/dashboard/[dashboardId]/_components/Cards/atoms/Input.tsx
  app/dashboard/[dashboardId]/_components/Cards/atoms/TextInput.tsx
  app/dashboard/[dashboardId]/_components/Cards/atoms/TextInputLabel.tsx
  app/dashboard/[dashboardId]/_components/Cards/molecules/ImageInput.tsx
  app/dashboard/[dashboardId]/_components/Cards/molecules/SelectInput.tsx
  app/dashboard/[dashboardId]/_components/Cards/molecules/TextInput.tsx
  app/dashboard/[dashboardId]/_components/Columns/ColumnModalTemplate.tsx
  app/dashboard/[dashboardId]/_components/Columns/CreateColumnModal/index.tsx
  app/dashboard/[dashboardId]/_components/Columns/DeleteColumnModal/index.tsx
  app/dashboard/[dashboardId]/_components/Columns/UpdateColumnModal/index.tsx
  app/dashboard/[dashboardId]/_components/Columns/commons/ColumnButton.tsx
  app/dashboard/[dashboardId]/_components/Columns/commons/ColumnButtonWrap.tsx
  app/dashboard/[dashboardId]/_components/Columns/commons/ColumnInput.tsx
  app/dashboard/[dashboardId]/_components/Columns/commons/ColumnModalTitle.tsx
Labels: feat, design

#67 Feat: 마이 대시보드 페이지 네이션, 무한 스크롤 구현
  .env
  app/mydashboard/Main.tsx
  app/mydashboard/_components/InvitationList/InvitationItem.tsx
  app/mydashboard/_components/InvitationList/index.tsx
  app/mydashboard/_components/MyDashboardList/DashboardItem.tsx
  app/mydashboard/_components/MyDashboardList/index.tsx
  app/mydashboard/_components/apis/api/index.ts
  app/mydashboard/_components/apis/instance/index.ts
  app/mydashboard/_components/commons/InvitationButton.tsx
  app/mydashboard/_components/commons/InvitationText.tsx
  app/mydashboard/_components/utils/index.ts
  app/mydashboard/page.tsx
  components/atoms/PageNationButton.tsx
Labels: feat

#71 Feat: 랜딩 페이지 라우팅 로직 구현
  .env
  app/_components/Navbar/index.tsx
  app/mydashboard/_components/apis/api/index.ts
Labels: feat

#76 Feat: 컬럼 생성,수정,삭제 모달 Modal hook이랑 연결
  app/dashboard/[dashboardId]/_components/Columns/ColumnModalTemplate.tsx
  app/dashboard/[dashboardId]/_components/Columns/CreateColumnModal/index.tsx
  app/dashboard/[dashboardId]/_components/Columns/DeleteColumnModal/index.tsx
  app/dashboard/[dashboardId]/_components/Columns/UpdateColumnModal/index.tsx
  app/dashboard/[dashboardId]/_components/Columns/commons/ModalDimmed.tsx
  app/dashboard/[dashboardId]/_components/molecules/ColumnAppendButton.tsx
  app/dashboard/[dashboardId]/_components/organisms/ColumnHeader.tsx
  app/test/page.tsx
  hooks/use-modal/modal-component/ModalList.tsx
Labels: feat

#84 마이 대시보드 무한 스크롤, 페이지 네이션 tanstack query로 리팩토링 및 대시보드 추가 모달 디자인, 테스트 로직
  app/_components/Navbar/index.tsx
  app/dashboard/[dashboardId]/_utils/prefetchDashboardList.query.ts
  app/mydashboard/_components/CreateDashboardModal/index.tsx
  app/mydashboard/_components/InvitationList/index.tsx
  app/mydashboard/_components/Main/Main.tsx
  app/mydashboard/_components/MyDashboardList/index.tsx
  app/mydashboard/_components/apis/api/index.ts
  app/mydashboard/_components/constants/index.ts
  app/mydashboard/_components/mock/mock.ts
  app/mydashboard/page.tsx
Labels: feat, design

#86 사이드바 페이지 네이션, 대시보드 클릭 로직 구현
  app/dashboard/layout.tsx
  app/mydashboard/_components/MyDashboardList/index.tsx
  app/mydashboard/page.tsx
  app/mypage/page.tsx
  components/atoms/ColoredDot.tsx
  components/constants/index.ts
  components/organisms/CreateDashboardModal.tsx
  components/organisms/SideBar/SideBar.tsx
Labels: feat, fix, refactor, design

#89 Feat: Navbar 제외하고 dashboard 및 dashboard edit 페이지 1차 완성
  .github/workflows/lint-check.yml
  apis/cards/getCardList.ts
  apis/dashboards/cancelDashboardInvitation.ts
  apis/instance/axiosToken.ts
  apis/members/deleteDashboardMember.ts
  apis/members/getDashboardMemberList.ts
  apis/users/getUserInfo.ts
  app/dashboard/[dashboardId]/_components/atoms/CardColumnBody.tsx
  app/dashboard/[dashboardId]/_components/atoms/ColumnContainer.tsx
  app/dashboard/[dashboardId]/_components/atoms/DashboardContentsArea.tsx
  app/dashboard/[dashboardId]/_components/molecules/ColumnProgressBar.tsx
  app/dashboard/[dashboardId]/_components/organisms/Card.tsx
  app/dashboard/[dashboardId]/_hooks/useGetCardListOnInfiniteScroll.query.ts
  app/dashboard/[dashboardId]/edit/_components/ContentArea/index.tsx
  app/dashboard/[dashboardId]/edit/_components/DashboardDeleteButton/index.tsx
  app/dashboard/[dashboardId]/edit/_components/DashboardInfoEditForm/index.tsx
  app/dashboard/[dashboardId]/edit/_components/EditPageWrapper/EditPageWrapper.tsx
  app/dashboard/[dashboardId]/edit/_components/InviteButton/index.tsx
  app/dashboard/[dashboardId]/edit/_components/InviteeListTable/index.tsx
  app/dashboard/[dashboardId]/edit/_components/InviteeManageForm/index.tsx
  app/dashboard/[dashboardId]/edit/_components/MemberListTable/index.tsx
  app/dashboard/[dashboardId]/edit/_components/MemberManageForm/index.tsx
  app/dashboard/[dashboardId]/edit/_hooks/useCancelDashboardInvitation.query.ts
  app/dashboard/[dashboardId]/edit/_hooks/useDeleteDashboardMember.query.ts
  app/dashboard/[dashboardId]/edit/_hooks/useGetInvitationList.query.ts
  app/dashboard/[dashboardId]/edit/_utils/prefetchDashboardInvitationList.query.ts
  app/dashboard/[dashboardId]/edit/page.tsx
  app/dashboard/_components/atoms/Page.tsx
  app/dashboard/_components/molecules/ContentsArea.tsx
  app/dashboard/_components/molecules/DashboardMemberList.tsx
  app/dashboard/_constants/mockDashboardMemberList.ts
  app/dashboard/_hooks/useGetDashboardMemberList.query.ts
  app/mydashboard/_components/Main/Main.tsx
  app/mypage/page.tsx
  app/signin/page.tsx
  components/atoms/CardTag.tsx
  components/organisms/.gitkeep
  components/organisms/CreateDashboardModal.tsx
  components/organisms/DashboardNameWithValidId.tsx
  components/organisms/DashboardNav.tsx
  components/organisms/SideBar/SideBar.tsx
  components/util/Funnel.tsx
  components/util/NonNullableFunnel.tsx
  components/util/withAuth.tsx
  hooks/use-modal/types.ts
  hooks/useToggle.ts
  interface/.gitkeep
  interface/util.ts
  middleware.ts
  queries/keys/cardsKeys.ts
  queries/keys/dashboardKeys.ts
  queries/keys/membersKeys.ts
  store/middleware/middleware.ts
  store/slice/userInfoSlice.ts
  store/store/userStore.ts
  store/user.js
  utils/token/getAccessToken.ts
Labels: feat

#95 Feat: dashboard navbar 완성
  .github/workflows/lint-check.yml
  apis/cards/getCardList.ts
  apis/dashboards/cancelDashboardInvitation.ts
  apis/instance/axiosToken.ts
  apis/members/deleteDashboardMember.ts
  apis/members/getDashboardMemberList.ts
  apis/users/getUserInfo.ts
  app/dashboard/[dashboardId]/_components/atoms/CardColumnBody.tsx
  app/dashboard/[dashboardId]/_components/atoms/ColumnContainer.tsx
  app/dashboard/[dashboardId]/_components/atoms/DashboardContentsArea.tsx
  app/dashboard/[dashboardId]/_components/molecules/ColumnProgressBar.tsx
  app/dashboard/[dashboardId]/_components/organisms/Card.tsx
  app/dashboard/[dashboardId]/_hooks/useGetCardListOnInfiniteScroll.query.ts
  app/dashboard/[dashboardId]/edit/_components/ContentArea/index.tsx
  app/dashboard/[dashboardId]/edit/_components/DashboardDeleteButton/index.tsx
  app/dashboard/[dashboardId]/edit/_components/DashboardInfoEditForm/index.tsx
  app/dashboard/[dashboardId]/edit/_components/EditPageWrapper/EditPageWrapper.tsx
  app/dashboard/[dashboardId]/edit/_components/InviteButton/index.tsx
  app/dashboard/[dashboardId]/edit/_components/InviteeListTable/index.tsx
  app/dashboard/[dashboardId]/edit/_components/InviteeManageForm/index.tsx
  app/dashboard/[dashboardId]/edit/_components/MemberListTable/index.tsx
  app/dashboard/[dashboardId]/edit/_components/MemberManageForm/index.tsx
  app/dashboard/[dashboardId]/edit/_hooks/useCancelDashboardInvitation.query.ts
  app/dashboard/[dashboardId]/edit/_hooks/useDeleteDashboardMember.query.ts
  app/dashboard/[dashboardId]/edit/_hooks/useGetInvitationList.query.ts
  app/dashboard/[dashboardId]/edit/_utils/prefetchDashboardInvitationList.query.ts
  app/dashboard/[dashboardId]/edit/page.tsx
  app/dashboard/_components/atoms/Page.tsx
  app/dashboard/_components/molecules/ContentsArea.tsx
  app/dashboard/_components/molecules/DashboardMemberList.tsx
  app/dashboard/_constants/mockDashboardMemberList.ts
  app/dashboard/_hooks/useGetDashboardMemberList.query.ts
  app/mydashboard/_components/Main/Main.tsx
  app/mypage/page.tsx
  app/signin/page.tsx
  components/atoms/CardTag.tsx
  components/organisms/.gitkeep
  components/organisms/CreateDashboardModal.tsx
  components/organisms/DashboardNameWithValidId.tsx
  components/organisms/DashboardNav.tsx
  components/organisms/SideBar/SideBar.tsx
  components/util/Funnel.tsx
  components/util/NonNullableFunnel.tsx
  components/util/withAuth.tsx
  hooks/use-modal/types.ts
  hooks/useToggle.ts
  interface/.gitkeep
  interface/util.ts
  middleware.ts
  queries/keys/cardsKeys.ts
  queries/keys/dashboardKeys.ts
  queries/keys/membersKeys.ts
  store/middleware/middleware.ts
  store/slice/userInfoSlice.ts
  store/store/userStore.ts
  store/user.js
  utils/token/getAccessToken.ts
Labels: feat

#96 Feat: dashboard protected route( dashboard, mydashboard, mypage 포함)
  .github/workflows/lint-check.yml
  apis/cards/getCardList.ts
  apis/dashboards/cancelDashboardInvitation.ts
  apis/instance/axiosToken.ts
  apis/members/deleteDashboardMember.ts
  apis/members/getDashboardMemberList.ts
  apis/users/getUserInfo.ts
  app/dashboard/[dashboardId]/_components/atoms/CardColumnBody.tsx
  app/dashboard/[dashboardId]/_components/atoms/ColumnContainer.tsx
  app/dashboard/[dashboardId]/_components/atoms/DashboardContentsArea.tsx
  app/dashboard/[dashboardId]/_components/molecules/ColumnProgressBar.tsx
  app/dashboard/[dashboardId]/_components/organisms/Card.tsx
  app/dashboard/[dashboardId]/_hooks/useGetCardListOnInfiniteScroll.query.ts
  app/dashboard/[dashboardId]/edit/_components/ContentArea/index.tsx
  app/dashboard/[dashboardId]/edit/_components/DashboardDeleteButton/index.tsx
  app/dashboard/[dashboardId]/edit/_components/DashboardInfoEditForm/index.tsx
  app/dashboard/[dashboardId]/edit/_components/EditPageWrapper/EditPageWrapper.tsx
  app/dashboard/[dashboardId]/edit/_components/InviteButton/index.tsx
  app/dashboard/[dashboardId]/edit/_components/InviteeListTable/index.tsx
  app/dashboard/[dashboardId]/edit/_components/InviteeManageForm/index.tsx
  app/dashboard/[dashboardId]/edit/_components/MemberListTable/index.tsx
  app/dashboard/[dashboardId]/edit/_components/MemberManageForm/index.tsx
  app/dashboard/[dashboardId]/edit/_hooks/useCancelDashboardInvitation.query.ts
  app/dashboard/[dashboardId]/edit/_hooks/useDeleteDashboardMember.query.ts
  app/dashboard/[dashboardId]/edit/_hooks/useGetInvitationList.query.ts
  app/dashboard/[dashboardId]/edit/_utils/prefetchDashboardInvitationList.query.ts
  app/dashboard/[dashboardId]/edit/page.tsx
  app/dashboard/_components/atoms/Page.tsx
  app/dashboard/_components/molecules/ContentsArea.tsx
  app/dashboard/_components/molecules/DashboardMemberList.tsx
  app/dashboard/_constants/mockDashboardMemberList.ts
  app/dashboard/_hooks/useGetDashboardMemberList.query.ts
  app/mydashboard/_components/Main/Main.tsx
  app/mypage/page.tsx
  app/signin/page.tsx
  components/atoms/CardTag.tsx
  components/organisms/.gitkeep
  components/organisms/CreateDashboardModal.tsx
  components/organisms/DashboardNameWithValidId.tsx
  components/organisms/DashboardNav.tsx
  components/organisms/SideBar/SideBar.tsx
  components/util/Funnel.tsx
  components/util/NonNullableFunnel.tsx
  components/util/withAuth.tsx
  hooks/use-modal/types.ts
  hooks/useToggle.ts
  interface/.gitkeep
  interface/util.ts
  middleware.ts
  queries/keys/cardsKeys.ts
  queries/keys/dashboardKeys.ts
  queries/keys/membersKeys.ts
  store/middleware/middleware.ts
  store/slice/userInfoSlice.ts
  store/store/userStore.ts
  store/user.js
  utils/token/getAccessToken.ts
Labels: feat

#97 Feat: dashboard 쿼리 훅 (빠뜨린) 부분 추가
  .github/workflows/lint-check.yml
  apis/cards/getCardList.ts
  apis/dashboards/cancelDashboardInvitation.ts
  apis/instance/axiosToken.ts
  apis/members/deleteDashboardMember.ts
  apis/members/getDashboardMemberList.ts
  apis/users/getUserInfo.ts
  app/dashboard/[dashboardId]/_components/atoms/CardColumnBody.tsx
  app/dashboard/[dashboardId]/_components/atoms/ColumnContainer.tsx
  app/dashboard/[dashboardId]/_components/atoms/DashboardContentsArea.tsx
  app/dashboard/[dashboardId]/_components/molecules/ColumnProgressBar.tsx
  app/dashboard/[dashboardId]/_components/organisms/Card.tsx
  app/dashboard/[dashboardId]/_hooks/useGetCardListOnInfiniteScroll.query.ts
  app/dashboard/[dashboardId]/edit/_components/ContentArea/index.tsx
  app/dashboard/[dashboardId]/edit/_components/DashboardDeleteButton/index.tsx
  app/dashboard/[dashboardId]/edit/_components/DashboardInfoEditForm/index.tsx
  app/dashboard/[dashboardId]/edit/_components/EditPageWrapper/EditPageWrapper.tsx
  app/dashboard/[dashboardId]/edit/_components/InviteButton/index.tsx
  app/dashboard/[dashboardId]/edit/_components/InviteeListTable/index.tsx
  app/dashboard/[dashboardId]/edit/_components/InviteeManageForm/index.tsx
  app/dashboard/[dashboardId]/edit/_components/MemberListTable/index.tsx
  app/dashboard/[dashboardId]/edit/_components/MemberManageForm/index.tsx
  app/dashboard/[dashboardId]/edit/_hooks/useCancelDashboardInvitation.query.ts
  app/dashboard/[dashboardId]/edit/_hooks/useDeleteDashboardMember.query.ts
  app/dashboard/[dashboardId]/edit/_hooks/useGetInvitationList.query.ts
  app/dashboard/[dashboardId]/edit/_utils/prefetchDashboardInvitationList.query.ts
  app/dashboard/[dashboardId]/edit/page.tsx
  app/dashboard/_components/atoms/Page.tsx
  app/dashboard/_components/molecules/ContentsArea.tsx
  app/dashboard/_components/molecules/DashboardMemberList.tsx
  app/dashboard/_constants/mockDashboardMemberList.ts
  app/dashboard/_hooks/useGetDashboardMemberList.query.ts
  app/mydashboard/_components/Main/Main.tsx
  app/mypage/page.tsx
  app/signin/page.tsx
  components/atoms/CardTag.tsx
  components/organisms/.gitkeep
  components/organisms/CreateDashboardModal.tsx
  components/organisms/DashboardNameWithValidId.tsx
  components/organisms/DashboardNav.tsx
  components/organisms/SideBar/SideBar.tsx
  components/util/Funnel.tsx
  components/util/NonNullableFunnel.tsx
  components/util/withAuth.tsx
  hooks/use-modal/types.ts
  hooks/useToggle.ts
  interface/.gitkeep
  interface/util.ts
  middleware.ts
  queries/keys/cardsKeys.ts
  queries/keys/dashboardKeys.ts
  queries/keys/membersKeys.ts
  store/middleware/middleware.ts
  store/slice/userInfoSlice.ts
  store/store/userStore.ts
  store/user.js
  utils/token/getAccessToken.ts
Labels: feat

#91 Feat: 컬럼 추가, 수정, 삭제 기능 구현
  apis/columns/createColumns.ts
  apis/columns/deleteColumn.ts
  apis/columns/updateColumn.ts
  app/_components/Navbar/index.tsx
  app/dashboard/[dashboardId]/_components/ColumContainerGroup/index.tsx
  app/dashboard/[dashboardId]/_components/Columns/CreateColumnModal/ColumnTitleInput.tsx
  app/dashboard/[dashboardId]/_components/Columns/CreateColumnModal/index.tsx
  app/dashboard/[dashboardId]/_components/Columns/CreateColumnModal/useColumnTitleInput.tsx
  app/dashboard/[dashboardId]/_components/Columns/CreateColumnModal/useCreateColumn.tsx
  app/dashboard/[dashboardId]/_components/Columns/DeleteColumnModal/index.tsx
  app/dashboard/[dashboardId]/_components/Columns/UpdateColumnModal/UpdateColumnTitleInput.tsx
  app/dashboard/[dashboardId]/_components/Columns/UpdateColumnModal/index.tsx
  app/dashboard/[dashboardId]/_components/Columns/UpdateColumnModal/useUpdateColumn.tsx
  app/dashboard/[dashboardId]/_components/Columns/UpdateColumnModal/useUpdateColumnTitleInput.tsx
  app/dashboard/[dashboardId]/_components/Columns/commons/ColumnButton.tsx
  app/dashboard/[dashboardId]/_components/Columns/commons/ColumnInput.tsx
  app/dashboard/[dashboardId]/_components/Columns/commons/ColumnModalTitile.tsx
  app/dashboard/[dashboardId]/_components/molecules/ColumnAppendButton.tsx
  app/dashboard/[dashboardId]/_components/organisms/ColumnHeader.tsx
  app/dashboard/[dashboardId]/page.tsx
  components/organisms/CreateDashboardModal.tsx
  utils/token/getAccessToken.ts
Labels: feat

#93 refactor: api 정리 및 여러가지 리팩토링, 빼먹은 기능 구현
  apis/dashboards/getDashboardList.ts
  apis/dashboards/getFirstDashboard.ts
  apis/invitations/getInitialInvitionList.ts
  apis/invitations/getMoreInvitionList.ts
  apis/invitations/getSearchedInvitationList.ts
  apis/invitations/putInvitationAnswer.ts
  app/_components/Main/index.tsx
  app/_components/Navbar/index.tsx
  app/_components/mock/index.ts
  app/mydashboard/_components/InvitationList/index.tsx
  app/mydashboard/_components/InvitationList/invitationItem/index.tsx
  app/mydashboard/_components/MyDashboardList/DashboardItem/index.tsx
  app/mydashboard/_components/MyDashboardList/index.tsx
  app/mydashboard/_components/apis/api/index.ts
  app/mydashboard/_components/apis/instance/index.ts
  app/mydashboard/_components/mock/mock.ts
  app/mydashboard/_components/utils/index.ts
  app/mydashboard/_constants/index.ts
  app/mydashboard/_utils/prefetchDashboardList.query.ts
  app/mydashboard/page.tsx
  components/organisms/CreateDashboardModal.tsx
  components/organisms/SideBar/SideBar.tsx
Labels: feat, fix, refactor

#102 Feat: 공용 컴포넌트 경로에 따른 분기처리 관리할 수 있는 Funnel 컴포넌트 생성, Spinner 컴포넌트
  app/dashboard/_components/molecules/DashboardMemberList.tsx
  app/dashboard/_components/molecules/DashboardMemberListWithFunnel.tsx
  components/atoms/FirstLetterProfile.tsx
  components/atoms/Spinner.tsx
  components/molecules/Input.tsx
  components/organisms/DashboardNav.tsx
  components/util/Funnel.tsx
  components/util/NonNullableFunnel.tsx
  components/util/returnBaseOnPathName.tsx
  components/util/withFunnel.tsx
  interface/util.ts
Labels: feat, fix

#100 마이대시보드 무한스크롤, 서치바 버그 수정
  apis/invitations/getInitialInvitionList.ts
  apis/invitations/getMoreInvitionList.ts
  app/mydashboard/_components/InvitationList/hook.tsx
  app/mydashboard/_components/InvitationList/index.tsx
  app/mydashboard/_components/InvitationList/invitationItem/index.tsx
  app/mydashboard/_components/MyDashboardList/hook.tsx
  app/mydashboard/_components/MyDashboardList/index.tsx
  app/mydashboard/_components/commons/spinner.tsx
  components/organisms/CreateDashboardModal.tsx
  components/organisms/SideBar/SideBar.tsx
  components/organisms/SideBar/hook.tsx
Labels: feat, fix, refactor

#101 대시보드 생성 모달 에러 메시지 구현 및 리팩토링
  app/dashboard/[dashboardId]/_components/Columns/commons/ColumnButton.tsx
  components/organisms/CreateDashboardModal.tsx
Labels: feat, refactor

#108 Feat: 대시보드 삭제 기능 구현 및 기타 버그들 수정
  app/dashboard/[dashboardId]/_components/organisms/Card.tsx
  app/dashboard/[dashboardId]/edit/_components/DashboardDeleteButton/index.tsx
  app/dashboard/[dashboardId]/edit/_components/MemberListTable/index.tsx
  app/dashboard/[dashboardId]/edit/_components/MemberManageForm/index.tsx
  app/dashboard/[dashboardId]/edit/_hooks/useDeleteDashboard.query.ts
  app/dashboard/[dashboardId]/edit/_hooks/usePaginationGetDashboardMemberList.query.ts
  app/dashboard/[dashboardId]/edit/page.tsx
  app/dashboard/_components/molecules/DashboardMemberList.tsx
  app/dashboard/_hooks/useGetDashboardMemberList.query.ts
  components/atoms/FirstLetterProfile.tsx
  components/organisms/DashboardNameWithValidId.tsx
  queries/keys/membersKeys.ts
Labels: feat, fix

#103 Feat: storybook
  .eslintrc.cjs
  .gitignore
  .storybook/main.ts
  .storybook/preview.tsx
  app/dashboard/_components/molecules/DashboardMemberList.tsx
  components/atoms/FirstLetterProfile/FirstLetterProfile.stories.tsx
  components/atoms/FirstLetterProfile/index.tsx
  components/molecules/ColorSelectList/ColorSelectList.stories.tsx
  package-lock.json
  package.json
Labels: feat

#116 Feat: 애플리케이션 전체 쿼리키 다시 매핑, 네브바 프로필 이미지 사진 prop넘김
  app/dashboard/[dashboardId]/_components/Columns/CreateColumnModal/useCreateColumn.tsx
  app/dashboard/[dashboardId]/_components/Columns/DeleteColumnModal/index.tsx
  app/dashboard/[dashboardId]/_components/Columns/UpdateColumnModal/useUpdateColumn.tsx
  app/dashboard/[dashboardId]/_components/atoms/NumberChip.tsx
  app/dashboard/[dashboardId]/_components/molecules/ColumnProgressBar.tsx
  app/dashboard/[dashboardId]/_components/organisms/Card.tsx
  app/dashboard/[dashboardId]/_hooks/useGetCardListOnInfiniteScroll.query.ts
  app/dashboard/[dashboardId]/edit/_components/MemberListTable/index.tsx
  app/dashboard/_components/molecules/DashboardMemberList.tsx
  queries/keys/cardsKeys.ts
  queries/keys/dashboardKeys.ts
Labels: feat, fix

#119 Feat: 전역적으로 mount 때마다 stale이 아니더라도 refetch하도록 변경
  apis/cards/putModifyCard.ts
  app/_modals/ToDoCardModal.tsx
  app/dashboard/[dashboardId]/_components/Cards/CreateCardsModal..tsx
  app/dashboard/[dashboardId]/_components/Columns/CreateColumnModal/useCreateColumn.tsx
  app/dashboard/[dashboardId]/_components/Columns/DeleteColumnModal/index.tsx
  app/dashboard/[dashboardId]/_components/Columns/UpdateColumnModal/index.tsx
  app/dashboard/[dashboardId]/_components/Columns/UpdateColumnModal/useUpdateColumn.tsx
  app/dashboard/[dashboardId]/_components/molecules/ColumnProgressBar.tsx
  app/dashboard/[dashboardId]/_components/organisms/ColumnHeader.tsx
  app/dashboard/[dashboardId]/_hooks/useGetCardList.query.ts
  app/dashboard/[dashboardId]/_hooks/useGetCardListOnInfiniteScroll.query.ts
  app/dashboard/[dashboardId]/_hooks/useGetColumnList.query.ts
  app/dashboard/[dashboardId]/_hooks/useObserveCardListQuery.query.ts
  app/dashboard/[dashboardId]/edit/_components/InviteButton/index.tsx
  app/dashboard/[dashboardId]/edit/_components/InviteeListTable/index.tsx
  app/dashboard/[dashboardId]/edit/_components/MemberListTable/index.tsx
  app/dashboard/[dashboardId]/edit/_hooks/useDeleteDashboard.query.ts
  app/dashboard/_components/molecules/InviteButton.tsx
  app/modaltest/ModifyCardsModal..tsx
  app/modaltest/ToDoCardModal.tsx
  app/mydashboard/_components/MyDashboardList/hook.tsx
  app/test/page.tsx
  components/atoms/FirstLetterProfile/FirstLetterProfile.stories.tsx
  components/atoms/FirstLetterProfile/index.tsx
  components/organisms/CreateDashboardModal.tsx
  components/organisms/DashboardNav.tsx
  components/organisms/SideBar/hook.tsx
  components/util/NonNullableFunnel.tsx
  components/util/returnBasedOnPathName.tsx
  components/util/withAuth.tsx
  components/util/withFunnel.tsx
  hooks/use-modal/types.ts
  hooks/use-modal/useModal.ts
  hooks/use-modal/useModalList.ts
  lib/tanstack-query/getQueryClient.ts
  queries/keys/cardsKeys.ts
  queries/keys/columnskeys.ts
  store/slice/userInfoSlice.ts
Labels: feat, fix
